export const vinyl = [
  {
    title: "Selling Dogma",
    artist: "The Clouds",
    price: 44.99,
    image: "./public/images/brad.png",
    year: 2003,
    genre: "rock",
    stock: 12,
  },
  {
    title: "Echoes in Transit",
    artist: "Silver Meadow",
    price: 38.59,
    image: "./public/images/central.png",
    year: 2012,
    genre: "indie",
    stock: 12,
  },
  {
    title: "Midnight Parallels",
    artist: "Neon Grove",
    price: 40.99,
    image: "./public/images/lilbaby.jpg",
    year: 2020,
    genre: "ambient",
    stock: 12,
  },
  {
    title: "Paper Skies",
    artist: "The Ivory Youth",
    price: 42.45,
    image: "./public/images/mic.jpg",
    year: 2010,
    genre: "rock",
    stock: 12,
  },
  {
    title: "Lost Cartography",
    artist: "Atlas Hills",
    price: 39.99,
    image: "./public/images/sza.jpg",
    year: 2007,
    genre: "folk",
    stock: 12,
  },
];
